theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
cursorline = true
#cursorcolumn = true
auto-save = true
bufferline = "always"
middle-click-paste = false
auto-pairs = true

[editor.indent-guides]
character = "|"
render = true

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"
#select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.file-picker]
hidden = false

[keys.insert]
"A-n" = "normal_mode"
"C-s" = ":w"

[keys.normal]
C-s = ":w"
#C-h = ""
#"C-/" = "comment"
"A-w" = ":wq"
"A-q" = ":q!"
"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"
"C-c" = ":buffer-close"
"A-/" = "repeat_last_motion"
